export enum Template {
  CACHE_VIEWER = 'CACHE_VIEWER',
  STATIC_DATA = 'STATIC_DATA',
  QUERY_EXECUTOR = 'QUERY_EXECUTOR',
  MUTATION_EXECUTOR = 'MUTATION_EXECUTOR',
  NESTED_TEMPLATE = 'NESTED_TEMPLATE',
  CUSTOM_QUERY = 'CUSTOM_QUERY',
  CUSTOM_MUTATION = 'CUSTOM_MUTATION',
  FETCH_AND_MUTATE = 'FETCH_AND_MUTATE',
  CUSTOM = 'CUSTOM',
}
