export enum Game {
  CURRENT_USER = 'CURRENT_USER',
  QUERY_EXECUTOR = 'QUERY_EXECUTOR',
  MUTATION_EXECUTOR = 'MUTATION_EXECUTOR',
  USER_PREFERENCES = 'USER_PREFERENCES',
  RECORD_MANAGER = 'RECORD_MANAGER',
}

export enum SubGame {
  RM_CREATE = 'RM_CREATE',
  RM_UPDATE = 'RM_UPDATE',
  RM_USER_PREF = 'RM_USER_PREF',
}
